### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by raghukiran1224** [erikerlandson/ray-odh-demo#1]
Hi,

Looking at the project, it appears that this is to get Ray working on OpenShift. Could you provide more info and how I can try this out?

**Comment by erikerlandson** [comment]
Hi, I appologize for not seeing this - I'm still experimenting, but I will add some doc when I have it in a coherent state

**Comment by raghukiran1224** [comment]
no problem @erikerlandson - I see you are part of RedHat. Happy to connect internally (am part of IBM). What's the best way to do so?

**Comment by erikerlandson** [comment]
Hi @raghukiran1224 my red hat email is: eje@redhat.com
